name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge-dependabot-prs:
    name: Auto-Merge Dependabot Dependency PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.DEV_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.DEV_AUTOMATION_PRIVATE_KEY }}

      - name: Comment to trigger Dependabot merge
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr comment $PR_NUMBER --body "@dependabot merge"
