name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "@dependabot merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
