name: CI

on:
  push:
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Build
        run: ./gradlew clean build --no-daemon --stacktrace

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start application
        run: docker compose up -d app
      - name: Health Check
        uses: emilioschepis/wait-for-endpoint@v1.0.4
        with:
          url: http://localhost:18080/health
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 1000
